# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "GDG QualityFest"
email: "contato@gdg-campinas.org"
description: "A maior conferencia sobre qualidade do interior de São Paulo abordará a qualidade de um produto (software) em diversos aspectos e trazer a consciência de que todos são responsáveis pela qualidade final."
baseurl: "/qualityfest-2017"
url: "https://gdg-campinas.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-campinas.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"
mapsApiKey: "AIzaSyBKggjiyNZRv2LMI86wSOAu2f2yZzUXArI"

aboutEvent:
  title: "SOBRE O QUALITYFEST"
  content: "A maior conferencia sobre qualidade do interior de São Paulo abordará a qualidade de um produto (software) em diversos aspectos e trazer a consciência de que todos são responsáveis pela qualidade final."
aboutGDG:
  title: "O QUE É O GDG?"
  content: "O GDG Campinas é parte de um programa do Google (Google Developer Group) sendo atualmente 1 de mais de 666 comunidades espalhadas pelo mundo. 
  <br> Possuimos o objetivo de proporcionar ambientes de compartilhamento de conhecimento sobre os mais diversos assuntos que permeiam o desenvolvimento de um produto (software), da maneira mais acessível a todos que estiverem dispostos a aprender e compartilhar conosco."

# Organizer Info
organizerName: "GDG Campinas"
organizerAlternateName: "Google Developer Group Campinas"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "contato@gdg-campinas.org"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://www.meetup.com/gdgcampinas/"

# Head
metaKeywords: "event, gdg, qualityfest, quality, fest, google, programming, developers, campinas"
twitterAccount: "@gdgcampinas"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
# c4pUrl: "https://bit.ly/dfua-c4p"
# c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Principal"}
 - {permalink: "/schedule/", text: "Agenda"}
 - {permalink: "/speakers/", text: "Palestrantes"}
#  - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/team/", text: "Time"}
#  - {permalink: "/logistics/", text: "Logistics"}
#  - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "https://www.eventbrite.com.br/e/quality-fest-17-tickets-36847465762", text: "Ingressos"}
rightNavigationButtons:
 - {link: "https://www.eventbrite.com.br/e/quality-fest-17-tickets-36847465762", text: "Ingressos"}

# Hero Block
heroImage: "bughipster.jpg"
heroTitle: "GDG <typeout> QualityFest 2017"
eventDate: "16 de Setembro de 2017"
typeoutTextValues: '"", "Campinas"'
typeoutFallback: "Campinas"
heroButtons:
#  - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Ingressos"}

# About Block
# aboutTitle: "About GDG DevFest"
# aboutBlock:
#  - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
#  - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
#  - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "150", specialCharacter: "+", info: "participantes", detail: "de Campinas e região"}
 - {count: "8", specialCharacter: "+", info: "horas", detail: "de muito networking e conteúdo de altíssima qualidade"}
 - {count: "18", specialCharacter: "", info: "palestrantes", detail: "referências no assunto"}
 - {count: "2", specialCharacter: "", info: "trilhas", detail: "simultâneas"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "background-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Destaque"
rockstarSpeakersButtonText: "Veja todos palestrantes"

# Location Block
# R. Dr. Ricardo Benetton Martins 1000 - Polo II de Alta Tecnologia, Campinas - SP, 13086-510
# Pólis de Tecnologia
locationBlockTitle: "Localização"
eventLocationName: "Weme"
eventLocationLink: "http://www.weme.nu/"
eventStreetAddress: "Av. Dr. Jesuíno Marcondes Machado, 630"
eventAddressLocality: "Campinas"
eventAddressLocalityRegion: "Nova Campinas"
eventPostalCode: "13092-108"
eventAddressCountry: "Brasil"
eventStartTime: ""
eventDoorTime: ""
eventEndTime: ""
eventPlaceCoordinates: "-22.901004,-47.042149"
mapCenterCoordinates: "-22.901004,-47.042149"
mapMobileCenterCoordinates: "-22.901004,-47.042149"

# Venue Block
venueBlockTitle: "Local"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Weme"
venueFeatures: ["Campinas"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Esperamos por você!"
twitterHashTag: "GDGQualityFest"
twitterFeed: "<< twitter_feed_url >>"
twitterHomeUrl: "https://twitter.com/gdgcampinas"

# Partners Block
organizersTitle: "Realização"
partnersTitle: "Patrocínio"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
# subscribeImage: "subscribe.jpg"
# subscribeTitle: "Subscribe for updates"
# subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
# subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Ingressos"
ticketsInfo: "Os ingressos dão acesso a todas as trilhas e coffee breaks."
ticketsOffers:
 -
  name: "Early Bird"
  price: "40,00"
  priceCurrency: "R$"
  ticketsNumber: "100"
  # ribbon: "-5%"
  buyButtonLink: "https://www.eventbrite.com.br/e/quality-fest-17-tickets-36847465762"
  buyButtonText: "Comprar"
  # ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "06/08/2017T19:30"
  validThrough: "30/08/2017T23:59"
  soldOut: true
  soldOutText: "Esgotado"
  disabled: true
 -
  name: "Ticket"
  price: "55,00"
  priceCurrency: "R$"
  ticketsNumber: "50"
  # ribbon: "-20%"
  # featured: true
  buyButtonLink: "https://www.eventbrite.com.br/e/quality-fest-17-tickets-36847465762"
  buyButtonText: "Comprar"
  # ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "27/08/2017T00:00"
  validThrough: "09/09/2017T23:59"
  soldOut: true
  soldOutText: "Esgotado"
  disabled: true
 -
  name: "Late Bird"
  price: "65,00"
  priceCurrency: "R$"
  ticketsNumber: "20"
  buyButtonLink: "https://www.eventbrite.com.br/e/quality-fest-17-tickets-36847465762"
  buyButtonText: "Comprar"
  # additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  # ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "09/09/2017T00:00"
  validThrough: "15/09/2017T23:59"
  disabled: true
  soldOut: true
  soldOutText: "Esgotado"

# Footer
socialLinks:
 - {link: "https://plus.google.com/+GDG-CampinasOrg", icon: "google-plus"}
 - {link: "https://twitter.com/gdgcampinas", icon: "twitter"}
 - {link: "https://www.facebook.com/gdgcampinas/", icon: "facebook"}
 - {link: "https://www.linkedin.com/company-beta/15240699/", icon: "linkedin"}
#  - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.meetup.com/gdgcampinas/", text: "Meetup"}
   - {link: "https://www.facebook.com/groups/gdgcampinas/", text: "Grupo Facebook"}
   - {link: "https://chat.whatsapp.com/H7KW7cqz9pVCbw9onN48qZ", text: "Whatsapp"}
 -
  title: "Contatos"
  links:
   - {link: "mailto:contato@gdg-campinas.org", text: "contato@gdg-campinas.org"}
#  -
#   title: "FAQ"
#   links:
#    - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
# blogTitle: "Latest news"
# blogCommentsEnabled: true
# discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Quem somos"
aboutUs: "O GDG Campinas é parte de um programa do Google (Google Developer Group) sendo atualmente 1 de mais de 666 comunidades espalhadas pelo mundo. 
  <br> Possuimos o objetivo de proporcionar ambientes de compartilhamento de conhecimento sobre os mais diversos assuntos que permeiam o desenvolvimento de um produto (software), da maneira mais acessível a todos que estiverem dispostos a aprender e compartilhar conosco."
teamOrganizerTitle: "Organizadores"

# Logistics Find Way Block
# findWayTitle: "Find your way here"
# findWayDistance: "Distance"
# findWayDriving: "DRIVING"
# findWayWalking: "WALKING"
# findWayBicycling: "BICYCLING"
# findWayTransit: "TRANSIT"
# findWayFindFlight: "Find Flight"
# logisticsMapCenterCoordinates: "49.056728, 3.117289"
# logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
# logisticsMapAutoDirections: false

# # Logistics Direction Details Block
# directionDetailsImage: "direction-details.jpg"
# directionDetailsTitle: "Get around Lviv"
# directionDetailsCards:
#  - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
#  - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
#  - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
# directionDetailsWideCards:
#  -
#   title: "Questions?"
#   subCards:
#    -
#     title: "Hotels"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#    -
#     title: "Registration"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#    -
#     title: "Attendance Details"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# # Hackathon
# hackathonTitle: "Hackathon"
# enableHackathon: true

# # Hackathon About Block
# aboutHackathonTitle: "Meet our themes"
# hackathonRows:
#  - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
#  - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
#  - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# # Hackathon Judges Block
# judgesImage: "judges.jpg"
# judgesTitle: "Judges"

# # Hackathon Prizes Block
# prizesTitle: "Prizes"
# prizes:
#  - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
#  - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
#  - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# # Hackathon Location Block
# hackathonLocationBlockTitle: "Location"
# hackathonLocationName: "Communa"
# hackathonLocationLink: "http://communa.net.ua/"
# hackathonStreetAddress: "1 Halytska St"
# hackathonAddressLocality: "Lviv"
# hackathonAddressLocalityRegion: "Lvivska"
# hackathonPostalCode: "79000"
# hackathonAddressCountry: "Ukraine"
# hackathonTimeTitle: "Hack through"
# hackathonStartTime: "2014-10-24T10:00"
# hackathonDoorTime: "09:00"
# hackathonEndTime: "2014-10-25T00:00"
# viewOnMap: "View on Google Maps"
# hackathonPlaceCoordinates: "49.840999, 24.031144"
# hackathonMapCenterCoordinates: "49.840696, 24.028754"
# hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
